// Dataset mockado para o Radar PID (protótipo).
// Inspirado em dados reais (ANEEL SIGA, Atlas E+, EDA interno) mas TODOS
// os números operacionais por município são estimativas/proxy para validar
// o fluxo de decisão. Substituir por master_df.csv real na próxima versão.
//
// instrumentosPublicos[]: badges de elegibilidade preliminar (TRIAGEM, não
// parecer jurídico). Categorias: fiscal | financiamento | leilao | obra | politica.

export const INSTRUMENTOS_LABELS = {
  REIDI: { categoria: "fiscal", nome: "REIDI", cor: "amber" },
  SUDENE: { categoria: "fiscal", nome: "SUDENE", cor: "amber" },
  SUDAM: { categoria: "fiscal", nome: "SUDAM", cor: "amber" },
  Debentures: { categoria: "fiscal", nome: "Debêntures inc.", cor: "amber" },
  FNE: { categoria: "financiamento", nome: "FNE", cor: "ember" },
  FNO: { categoria: "financiamento", nome: "FNO", cor: "ember" },
  FCO: { categoria: "financiamento", nome: "FCO", cor: "ember" },
  BNDES: { categoria: "financiamento", nome: "BNDES", cor: "ember" },
  Leilao: { categoria: "leilao", nome: "Leilão ANEEL", cor: "ember" },
  PNCP: { categoria: "leilao", nome: "PNCP", cor: "ember" },
  Transferegov: { categoria: "obra", nome: "Transferegov", cor: "moss" },
  Obrasgov: { categoria: "obra", nome: "Obrasgov", cor: "moss" },
  PAC: { categoria: "obra", nome: "Novo PAC", cor: "moss" },
  REDATA: { categoria: "politica", nome: "Pol. Data Centers", cor: "amber" },
};

export const CATEGORIAS_INSTRUMENTOS = {
  fiscal: { label: "Incentivo fiscal", glifo: "₣" },
  financiamento: { label: "Financiamento", glifo: "$" },
  leilao: { label: "Leilão / contratação", glifo: "⇄" },
  obra: { label: "Obra / transferência", glifo: "▣" },
  politica: { label: "Política setorial", glifo: "§" },
};

export const MUNICIPIOS = [
  {
    id: "pecem-ce",
    municipio: "São Gonçalo do Amarante",
    apelido: "Pecém",
    uf: "CE",
    lat: -3.611,
    lng: -38.968,
    capacidadeRenovavelMw: 6562,
    solarMw: 2132,
    eolicaMw: 2690,
    hidroMw: 0,
    pipelineMw: 9800,
    margemRedeMw: 1850,
    distanciaSubestacaoKm: 4,
    distanciaFibraKm: 8,
    demandaIndustrialScore: 88,
    riscoSocioambientalScore: 22,
    desenvolvimentoRegionalScore: 71,
    prontidaoDataCenterScore: 82,
    convergenciaPublicaScore: 86,
    instrumentosPublicos: ["REIDI", "SUDENE", "FNE", "Debentures", "BNDES", "REDATA", "PAC"],
    observacoes:
      "Hub de hidrogênio verde + porto operacional + 41% das iniciativas H₂ do país. Pipeline solar/eólico 9,8 GW.",
    dadosMockados: true,
  },
  {
    id: "janauba-mg",
    municipio: "Janaúba",
    apelido: null,
    uf: "MG",
    lat: -15.803,
    lng: -43.309,
    capacidadeRenovavelMw: 2104,
    solarMw: 2104,
    eolicaMw: 0,
    hidroMw: 0,
    pipelineMw: 1200,
    margemRedeMw: 410,
    distanciaSubestacaoKm: 12,
    distanciaFibraKm: 35,
    demandaIndustrialScore: 28,
    riscoSocioambientalScore: 18,
    desenvolvimentoRegionalScore: 84,
    prontidaoDataCenterScore: 41,
    convergenciaPublicaScore: 68,
    instrumentosPublicos: ["SUDENE", "FNE", "REIDI", "Debentures"],
    observacoes:
      "Solar dominante. Indústria local mínima — fronteira de powershoring para neoindustrialização.",
    dadosMockados: true,
  },
  {
    id: "buritizeiro-mg",
    municipio: "Buritizeiro",
    apelido: null,
    uf: "MG",
    lat: -17.349,
    lng: -44.962,
    capacidadeRenovavelMw: 1208,
    solarMw: 920,
    eolicaMw: 0,
    hidroMw: 288,
    pipelineMw: 4465,
    margemRedeMw: 720,
    distanciaSubestacaoKm: 9,
    distanciaFibraKm: 42,
    demandaIndustrialScore: 24,
    riscoSocioambientalScore: 26,
    desenvolvimentoRegionalScore: 78,
    prontidaoDataCenterScore: 38,
    convergenciaPublicaScore: 64,
    instrumentosPublicos: ["SUDENE", "FNE", "REIDI", "BNDES"],
    observacoes:
      "Pipeline solar de 4,5 GW outorgado, sem indústria local. Top-3 em mismatch energia/indústria.",
    dadosMockados: true,
  },
  {
    id: "camacari-ba",
    municipio: "Camaçari",
    apelido: null,
    uf: "BA",
    lat: -12.697,
    lng: -38.324,
    capacidadeRenovavelMw: 940,
    solarMw: 540,
    eolicaMw: 380,
    hidroMw: 20,
    pipelineMw: 1400,
    margemRedeMw: 280,
    distanciaSubestacaoKm: 3,
    distanciaFibraKm: 6,
    demandaIndustrialScore: 92,
    riscoSocioambientalScore: 38,
    desenvolvimentoRegionalScore: 52,
    prontidaoDataCenterScore: 67,
    convergenciaPublicaScore: 78,
    instrumentosPublicos: ["REIDI", "SUDENE", "FNE", "BNDES", "Debentures", "PNCP"],
    observacoes:
      "Polo petroquímico em transição. Demanda industrial existente alta, gargalo é margem de rede.",
    dadosMockados: true,
  },
  {
    id: "serra-do-mel-rn",
    municipio: "Serra do Mel",
    apelido: null,
    uf: "RN",
    lat: -5.184,
    lng: -37.052,
    capacidadeRenovavelMw: 1633,
    solarMw: 410,
    eolicaMw: 1223,
    hidroMw: 0,
    pipelineMw: 2200,
    margemRedeMw: 590,
    distanciaSubestacaoKm: 14,
    distanciaFibraKm: 38,
    demandaIndustrialScore: 19,
    riscoSocioambientalScore: 16,
    desenvolvimentoRegionalScore: 88,
    prontidaoDataCenterScore: 36,
    convergenciaPublicaScore: 72,
    instrumentosPublicos: ["SUDENE", "FNE", "REIDI", "Debentures", "Transferegov"],
    observacoes:
      "Eólica forte. Município com baixíssima indústria — ideal para política pública de atração industrial.",
    dadosMockados: true,
  },
  {
    id: "sento-se-ba",
    municipio: "Sento Sé",
    apelido: null,
    uf: "BA",
    lat: -9.745,
    lng: -41.881,
    capacidadeRenovavelMw: 1514,
    solarMw: 380,
    eolicaMw: 1134,
    hidroMw: 0,
    pipelineMw: 1860,
    margemRedeMw: 510,
    distanciaSubestacaoKm: 18,
    distanciaFibraKm: 56,
    demandaIndustrialScore: 14,
    riscoSocioambientalScore: 14,
    desenvolvimentoRegionalScore: 86,
    prontidaoDataCenterScore: 28,
    convergenciaPublicaScore: 70,
    instrumentosPublicos: ["SUDENE", "FNE", "REIDI", "Transferegov"],
    observacoes:
      "Sertão eólico. Povo local com baixo IDH — score de desenvolvimento regional muito alto.",
    dadosMockados: true,
  },
  {
    id: "altamira-pa",
    municipio: "Altamira",
    apelido: "Belo Monte",
    uf: "PA",
    lat: -3.203,
    lng: -52.205,
    capacidadeRenovavelMw: 11253,
    solarMw: 0,
    eolicaMw: 0,
    hidroMw: 11253,
    pipelineMw: 0,
    margemRedeMw: 1280,
    distanciaSubestacaoKm: 6,
    distanciaFibraKm: 95,
    demandaIndustrialScore: 11,
    riscoSocioambientalScore: 78,
    desenvolvimentoRegionalScore: 48,
    prontidaoDataCenterScore: 22,
    convergenciaPublicaScore: 58,
    instrumentosPublicos: ["SUDAM", "FNO", "REIDI", "BNDES"],
    observacoes:
      "Belo Monte. Capacidade hidroelétrica enorme, mas alto risco socioambiental e fibra distante.",
    dadosMockados: true,
  },
  {
    id: "tucurui-pa",
    municipio: "Tucuruí",
    apelido: null,
    uf: "PA",
    lat: -3.766,
    lng: -49.673,
    capacidadeRenovavelMw: 8536,
    solarMw: 0,
    eolicaMw: 0,
    hidroMw: 8536,
    pipelineMw: 0,
    margemRedeMw: 940,
    distanciaSubestacaoKm: 8,
    distanciaFibraKm: 72,
    demandaIndustrialScore: 18,
    riscoSocioambientalScore: 64,
    desenvolvimentoRegionalScore: 56,
    prontidaoDataCenterScore: 31,
    convergenciaPublicaScore: 56,
    instrumentosPublicos: ["SUDAM", "FNO", "REIDI", "BNDES", "PAC"],
    observacoes:
      "Hidrelétrica histórica. Margem de rede sub-utilizada para indústria de baixo carbono.",
    dadosMockados: true,
  },
  {
    id: "porto-velho-ro",
    municipio: "Porto Velho",
    apelido: null,
    uf: "RO",
    lat: -8.762,
    lng: -63.903,
    capacidadeRenovavelMw: 7537,
    solarMw: 17,
    eolicaMw: 0,
    hidroMw: 7520,
    pipelineMw: 0,
    margemRedeMw: 820,
    distanciaSubestacaoKm: 5,
    distanciaFibraKm: 24,
    demandaIndustrialScore: 22,
    riscoSocioambientalScore: 52,
    desenvolvimentoRegionalScore: 64,
    prontidaoDataCenterScore: 44,
    convergenciaPublicaScore: 62,
    instrumentosPublicos: ["SUDAM", "FNO", "REIDI", "BNDES", "Obrasgov"],
    observacoes:
      "Santo Antônio + Jirau. Capital — fibra disponível, único do Norte com prontidão razoável a data center.",
    dadosMockados: true,
  },
  {
    id: "rio-verde-go",
    municipio: "Rio Verde",
    apelido: null,
    uf: "GO",
    lat: -17.796,
    lng: -50.927,
    capacidadeRenovavelMw: 410,
    solarMw: 380,
    eolicaMw: 0,
    hidroMw: 30,
    pipelineMw: 720,
    margemRedeMw: 320,
    distanciaSubestacaoKm: 7,
    distanciaFibraKm: 14,
    demandaIndustrialScore: 58,
    riscoSocioambientalScore: 28,
    desenvolvimentoRegionalScore: 62,
    prontidaoDataCenterScore: 54,
    convergenciaPublicaScore: 60,
    instrumentosPublicos: ["FCO", "BNDES", "REIDI", "Debentures"],
    observacoes:
      "Polo agroindustrial do Centro-Oeste. Biomassa abundante, sem biometano operacional.",
    dadosMockados: true,
  },
  {
    id: "lucas-rio-verde-mt",
    municipio: "Lucas do Rio Verde",
    apelido: null,
    uf: "MT",
    lat: -13.054,
    lng: -55.911,
    capacidadeRenovavelMw: 320,
    solarMw: 280,
    eolicaMw: 0,
    hidroMw: 40,
    pipelineMw: 1100,
    margemRedeMw: 240,
    distanciaSubestacaoKm: 11,
    distanciaFibraKm: 28,
    demandaIndustrialScore: 51,
    riscoSocioambientalScore: 34,
    desenvolvimentoRegionalScore: 70,
    prontidaoDataCenterScore: 42,
    convergenciaPublicaScore: 58,
    instrumentosPublicos: ["FCO", "BNDES", "REIDI", "Debentures", "Transferegov"],
    observacoes:
      "MT produz 44 Mt soja/ano e tem zero biometano. Vazio do Centro-Oeste — caso de fertilizante verde.",
    dadosMockados: true,
  },
  {
    id: "barcarena-pa",
    municipio: "Barcarena",
    apelido: null,
    uf: "PA",
    lat: -1.553,
    lng: -48.622,
    capacidadeRenovavelMw: 480,
    solarMw: 12,
    eolicaMw: 0,
    hidroMw: 468,
    pipelineMw: 200,
    margemRedeMw: 380,
    distanciaSubestacaoKm: 4,
    distanciaFibraKm: 18,
    demandaIndustrialScore: 81,
    riscoSocioambientalScore: 58,
    desenvolvimentoRegionalScore: 60,
    prontidaoDataCenterScore: 51,
    convergenciaPublicaScore: 74,
    instrumentosPublicos: ["SUDAM", "FNO", "REIDI", "BNDES", "Obrasgov", "PAC"],
    observacoes:
      "Polo de alumínio (Albras/Hydro). Porto. Demanda industrial alta, mas risco socioambiental amazônico.",
    dadosMockados: true,
  },
];

export const PESO_DEFAULTS = {
  recurso: 0.22,
  rede: 0.18,
  demanda: 0.18,
  risco: 0.14,
  desenvolvimento: 0.14,
  datacenter: 0.14,
};

// Modos de análise — ajustam pesos automaticamente
export const MODOS = {
  renovaveis: {
    label: "Renováveis gerais",
    descricao: "Score balanceado para investimento em geração renovável.",
    pesos: { ...PESO_DEFAULTS },
  },
  data_centers: {
    label: "Data centers de IA",
    descricao: "Prioriza conexão à rede, prontidão digital e baixo risco.",
    pesos: {
      recurso: 0.16,
      rede: 0.22,
      demanda: 0.1,
      risco: 0.18,
      desenvolvimento: 0.08,
      datacenter: 0.26,
    },
  },
  neoindustrializacao: {
    label: "Neoindustrialização verde",
    descricao: "Prioriza recurso renovável, demanda existente e desenvolvimento regional.",
    pesos: {
      recurso: 0.26,
      rede: 0.16,
      demanda: 0.22,
      risco: 0.1,
      desenvolvimento: 0.2,
      datacenter: 0.06,
    },
  },
};

export const INSIGHTS_HEADER = [
  "PA lidera H2 Verde — Pecém com score 0,61, 4 dos top 5 em PA e MG.",
  "REIDI 2025 aprovou 47 novos projetos renováveis, 60% no Nordeste.",
  "Biometano: 51% da capacidade outorgada está ociosa — gargalo a destravar.",
  "Vale do Aço: oportunidade biometano-siderurgia mapeada em 4 municípios.",
];

export const CRITERIOS = [
  { id: "recurso", label: "Energia renovável", abrev: "energia" },
  { id: "rede", label: "Acesso à rede", abrev: "rede" },
  { id: "demanda", label: "Demanda local", abrev: "demanda" },
  { id: "risco", label: "Segurança socioambiental", abrev: "social" },
  { id: "desenvolvimento", label: "Impacto regional", abrev: "regional" },
  { id: "datacenter", label: "Infraestrutura digital", abrev: "digital" },
];
